format = """
$username\
$hostname\
$shlvl\
$directory\
$fill\
$git_branch\
$git_status\
$git_state\
$package\
$golang\
$java\
$python\
$rust\
$terraform\
$nix_shell\
$time\
$cmd_duration\
$line_break\
$jobs\
$status\
$character\
"""

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
style = "#BF616A"

[character]
success_symbol = "[❯](#D8DEE9) "
error_symbol = "[❯](#BF616A) "
vicmd_symbol = "[❮](#D8DEE9) "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncate_to_repo = false
truncation_symbol = "⋯ /"
style = 'bold #ECEFF4'

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

[git_branch]
style = '#5E81AC'
format = '[$symbol$branch]($style) '

[git_status]
style = '218'
format = '([$all_status]($style)[$ahead_behind](cyan) )'

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
style = '#81A1C1'
disabled = true
symbol = '⎈'
format = ' [$symbol $context:$namespace]($style) '

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "

[shlvl]
disabled = false
symbol = "§"
threshold = 3

[status]
disabled = false
style = '#BF616A'
format = '[$symbol$status]($style) '
map_symbol = true

[swift]
symbol = "ﯣ "

[time]
disabled = false
style = "#B48EAD"
